iotBase:
  parent-id: 91330203MA2GU7TQ52
  token-ak: bmJ4cnBsYXRmb3Jt
  token-sk: U0tfbmJ4cnBsYXRmb3Jt

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    baseline-on-migrate: true