server:
  port: 5555

spring:
  application:
    name: dahua
  profiles:
    include: iotBase, dahua
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 9999
    password: 123456
    host: localhost
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            isClustered: false  # 关闭集群模式
            tablePrefix: QRTZ_  # 指定数据库表的前缀
            misfireThreshold: 60000  # 设置过期时间（毫秒）
          threadPool:
            threadCount: 10  # 设置线程池大小
          scheduler:
            instanceId: AUTO  # 自动生成实例ID，多个节点共享
            instanceName: MyScheduler  # 为调度器实例指定名称

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: is_del
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement

